# Generated by Django 2.2.16 on 2023-02-25 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_favorite_shoppingcart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
    ]
