# Generated by Django 2.2.16 on 2023-02-25 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_subscription'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscription',
            new_name='Follow',
        ),
    ]
